// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6l2DtcTYptLy7rkGH3x-1a3ZbFwynxA',
    appId: '1:968592954033:web:185edb35c33606d6b14890',
    messagingSenderId: '968592954033',
    projectId: 'flutter-task-sws',
    authDomain: 'flutter-task-sws.firebaseapp.com',
    storageBucket: 'flutter-task-sws.appspot.com',
    measurementId: 'G-W7N369RZVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQhTIMDXkcUzUDLUrSXwsB_EqqANTAhIQ',
    appId: '1:968592954033:android:4813e37e7e01285ab14890',
    messagingSenderId: '968592954033',
    projectId: 'flutter-task-sws',
    storageBucket: 'flutter-task-sws.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOL6t9JeIDqkOO_Oj6NPb8MS-ncQpwCYk',
    appId: '1:968592954033:ios:caafd78d352c0d82b14890',
    messagingSenderId: '968592954033',
    projectId: 'flutter-task-sws',
    storageBucket: 'flutter-task-sws.appspot.com',
    androidClientId: '968592954033-n28iuh7t0nfboor66pj60r4qthktdp2t.apps.googleusercontent.com',
    iosClientId: '968592954033-1ll60i4gabtcuoln8rel1gi48hb4h2qf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOL6t9JeIDqkOO_Oj6NPb8MS-ncQpwCYk',
    appId: '1:968592954033:ios:483f7e460ed146a7b14890',
    messagingSenderId: '968592954033',
    projectId: 'flutter-task-sws',
    storageBucket: 'flutter-task-sws.appspot.com',
    androidClientId: '968592954033-n28iuh7t0nfboor66pj60r4qthktdp2t.apps.googleusercontent.com',
    iosClientId: '968592954033-6ifevkulmpivo3et05d5l728ffar8khd.apps.googleusercontent.com',
    iosBundleId: 'com.example.sws.RunnerTests',
  );
}
